package com.LMS.LMS.dto;

import lombok.Builder;
import lombok.Data;
import java.util.List;
import java.util.Map;

@Data
@Builder
public class AIReportResponse {

    // A natural language summary of the findings (generated by AI)
    private String summary;

    // Header names for the table (e.g., ["Student ID", "Books Read", "Total Fine"])
    private List<String> tableHeaders;

    // The actual data rows. Each map represents one row (e.g., {"Student ID": "S-101", "Books Read": 15})
    private List<Map<String, Object>> tableData;

    private String generatedAt;
}