// backend/com/LMS/LMS/dto/LateReturnDTO.java

package com.LMS.LMS.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LateReturnDTO {
    private String studentId;
    private String studentName;
    private int totalLateReturns;
    private double totalFines;
    private double avgDaysLate;
    // Getters and Setters are generated by Lombok @Data
}